### ISSUE TITLE
Recieve message function?

### ISSUE THREAD

**Issue by inzamam-idrees** [rpaschoal/ng-chat#146]
How can I recieve message from server?

**Comment by rpaschoal** [comment]
Hi @inzamam-idrees , 

Please check the example projects here on these repositories:

https://github.com/rpaschoal/ng-chat-netcoreapp
https://github.com/rpaschoal/ng-chat-nodejs

Hope this help, cheers!

**Comment by inzamam-idrees** [comment]
Hi @rpaschoal,

Thanks for reply to me I have to implement the chat feature in my project. This package is very useful to me and I already read your mention examples but my problem is different.

I am not using 'ng-socket-io' package I have to use pusher to recieve messages and when user1 send message to user2 then user2 recieve the notification using the channel but I want to know how I can recieve message in the chatbox of ng-chat.

**Comment by anouar1991** [comment]
Hi @inzamam-idrees, 
Most probably you need to understand how pusher-angular works and implement a ChatAdapter that uses pusher-angular instead of ng-socket-io.
Read section ( ** [Implement your ChatAdapter](https://www.npmjs.com/package/ng-chat) ** )
Here's : [pusher-angular](https://www.npmjs.com/package/pusher-angular)
Cheers
