### ISSUE TITLE
change css

### ISSUE THREAD

**Issue by eddy2enam** [rpaschoal/ng-chat#29]
how to change postion Friend list to left side and change width and height?
thanks

**Comment by rpaschoal** [comment]
Hi @eddy2enam,

At the moment there is no setting to change the friends list to the left side of the screen. The width and height could be changed, but for that time being that would mean everyone using the package would be affected as they are just private properties used in the viewport calculation.

There is a bit of work going on behind the scenes regarding viewport size and the size of the friend list and each window in order to calculate how many windows may be opened at the same time.

Could you give a bit more details of your requirements? Perhaps we can figure something out to make the UI and styles more flexible and customizable.

Cheers!

**Comment by rpaschoal** [comment]
Closing this issue as I am carrying over the discussion to #37

**Comment by duzenko** [comment]
@rpaschoal please reopen
still no good way to open chat from the left side
