### ISSUE TITLE
Responsive Chat window

### ISSUE THREAD

**Issue by sprakash1993** [rpaschoal/ng-chat#60]
It was nice to use the library. It works great. 

In the lower resolution (for mobile or ipad), the chat window is not visible. Is there a way to make it responsive so that it works for lower resolution as well ? 

Thanks

**Comment by rpaschoal** [comment]
Hi @sprakash1993 ,

I am glad you like the library!

That is by design, if you don't have enough space to see at least one window, the user experience would be degraded and that is why the component is not shown.

My advice for you would be to use another message exchange page within your application, something more mobile friendly.

Welcome to suggestions though, if you come up with an idea that might benefit everyone on a smaller device that would be great.

Cheers!
