### ISSUE TITLE
[Feature] Enable customisation

### ISSUE THREAD

**Issue by shaychoo** [rpaschoal/ng-chat#65]
this project is grate!
i'd miss some customisation options:
 
- hide the search input
- hide the friends list and pop chat window by click on icon e.g in HelpDesk support chat

**Comment by rpaschoal** [comment]
Hi @shaychoo ,

I am glad you like it!

Some of the suggested items I already had in mind, like popping the window to a draggable chat window on the viewport. Haven't found the time to implement it yet.

About hiding the friends list, do you mean minimizing it? If so, that is already a feature, all you have to do is click on its title.

**Comment by rpaschoal** [comment]
Hi @krytthew,

This is not a feature at the moment as you've mentioned, but we can implement it for sure, I am sure it will be helpful for other people in the future too. We could add command events to open, close and minimize a window from outside the module.

Would you be able to implement it and send a PR? Otherwise I can do it, but it might take a while for me to push the changes as I am quite busy with my personal life atm.

Cheers!

**Comment by rpaschoal** [comment]
Hi @krytthew,

Haven't heard back from you on this, but just to keep you and everyone else that might end up in this issue updated, `1.0.15` has just been released and this can be done in a better way.

Just check out the instructions in the main README on how to use `IChatController` for triggering actions outside of ng-chat.

Closing this issue as it is now officially supported and documented.
